version: '3'

services:
  web:
    image: nginx:1.23.4
    container_name: web
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./container/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./container/nginx/log:/var/log/nginx
      - ./backend/public:/backend/public
      - ./backend/tmp:/backend/tmp
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: container/frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: yarn dev
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: container/backend/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - '3001:3000'
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
      - PGTZ=Asia/Tokyo
      - POSTGRES_PASSWORD=password
    volumes:
      - ./container/db/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
